apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: toggle-master
spec:
  type: ClusterIP
  selector:
    app: analytics
  ports:
    - protocol: TCP
      port: 8005         
      targetPort: 8005
