apiVersion: v1
kind: Service
metadata:
  name: service-a
  namespace: default
  labels: { app: service-a }
spec:
  type: ClusterIP
  selector:
    app: service-a
  ports:
    - name: https
      port: 8443
      targetPort: 8443
