apiVersion: v1
kind: Pod

metadata:
  name: analytics-pod
  namespace: toggle-master
  labels:
    app: analytics
    tier: backend

spec:
  containers:
    - name: analytics-container
      image: kind-registry:5000/toggle-master-microservices-analytics-service
      imagePullPolicy: Always
      ports:
        - containerPort: 8005
      env:
        - name: AWS_REGION
          value: us-east-1
        - name: AWS_ACCESS_KEY_ID
          value: test
        - name: AWS_SECRET_ACCESS_KEY
          value: test
        - name: AWS_ENDPOINT_URL
          value: http://172.21.0.1:4566 # 172.21.0.1 (gateway kind)
        - name: AWS_DYNAMODB_TABLE
          value: analytics_events
        - name: AWS_SQS_URL
          value: http://172.21.0.1:4566/000000000000/toggle-analytics-queue
        - name: PORT
          value: "8005"
      resources:
        limits:
          memory: "256Mi"
          cpu: "500m"
        requests:
          memory: "128Mi"
          cpu: "250m"
