apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: toggle-master
spec:
  type: ClusterIP
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 8001         
      targetPort: 8001
