apiVersion: v1
kind: Service
metadata:
  name: evaluation-service
  namespace: toggle-master
spec:
  type: ClusterIP
  selector:
    app: evaluation
  ports:
    - protocol: TCP
      port: 8004
      targetPort: 8004
