apiVersion: v1
kind: Service
metadata:
  name: datadog-agent
  namespace: monitoring
spec:
  selector:
    app: datadog-agent
  ports:
    - name: apm
      port: 8126
      targetPort: 8126
      protocol: TCP
  clusterIP: None
