apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-deployment
  namespace: toggle-master
  labels:
    app: analytics
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics
      tier: backend
  template:
    metadata:
      labels:
        app: analytics
        tier: backend
    spec:
      containers:
        - name: analytics-container
          image: kind-registry:5000/toggle-master-microservices-analytics-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8005
          envFrom:
            - configMapRef:
                name: analytics-config
            - secretRef:
                name: analytics-secret
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"
