apiVersion: apps/v1
kind: Deployment

metadata:
  name: auth-deployment
  namespace: toggle-master
  labels:
    app: auth
    tier: backend

spec:
  replicas: 2

  selector:
    matchLabels:
      app: auth
      tier: backend

  template:
    metadata:
      labels:
        app: auth
        tier: backend

    spec:
      containers:
        - name: auth-container
          image: kind-registry:5000/toggle-master-microservices-auth-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
          env:
            - name: PORT
              value: "8001"
            - name: DATABASE_URL
              value: "postgresql://toggleuser:password@172.21.0.1:5433/togglemasterauth"
            - name: MASTER_KEY
              value: "01cf4be5-5270-41ff-86fe-0ce789440f04"
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"
