apiVersion: apps/v1
kind: Deployment
metadata:
  name: targeting-deployment
  namespace: toggle-master
  labels:
    app: targeting
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: targeting
      tier: backend
  template:
    metadata:
      labels:
        app: targeting
        tier: backend
    spec:
      containers:
        - name: targeting-container
          image: kind-registry:5000/toggle-master-microservices-targeting-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8003
          envFrom:
            - configMapRef:
                name: targeting-config
            - secretRef:
                name: targeting-secret
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"
