apiVersion: v1
kind: Service
metadata:
  name: donation-service
  namespace: solidary-tech
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8082"
    prometheus.io/path: "/metrics"
  labels:
    app: donation
spec:
  type: ClusterIP
  selector:
    app: donation
  ports:
    - protocol: TCP
      port: 8082         
      targetPort: 8082
