apiVersion: v1
kind: Service
metadata:
  name: volunteer-service
  namespace: solidary-tech
  labels:
    app: volunteer
spec:
  type: ClusterIP
  selector:
    app: volunteer
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
