apiVersion: v1
kind: Secret
metadata:
  name: analytics-secret
  namespace: toggle-master
type: Opaque
data:
  AWS_ACCESS_KEY_ID: dGVzdA==
  AWS_SECRET_ACCESS_KEY: dGVzdA==
  AWS_SESSION_TOKEN: dGVzdA==
  AWS_DYNAMODB_TABLE: YW5hbHl0aWNzX2V2ZW50cw==
  AWS_SQS_URL: aHR0cDovLzE3Mi4yMS4wLjE6NDU2Ni8wMDAwMDAwMDAwMDAvdG9nZ2xlLWFuYWx5dGljcy1xdWV1ZQ==
