apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/instance: solidary-tech
    release: prometheus
  name: solidary-tech-backend-monitors
  namespace: solidary-tech
spec:
  endpoints:
    - interval: 15s
      path: /metrics
      port: http
      scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
      - solidary-tech
      - toggle-master
  selector:
    matchLabels:
      tier: backend
