apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: solidary-tools-ingress
  namespace: solidary-tech
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: acb765565fcce482687878702061fc47-f0d0f5c54c859cc3.elb.us-east-1.amazonaws.com
      http:
        paths:
          - path: /prometheus(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: prometheus-internal-link
                port:
                  number: 9090
