apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: solidary-tech-ingress
  namespace: solidary-tech
spec:
  ingressClassName: nginx
  rules:
    - host: a01b029fc04b346b6bb412500c0630c0-13a8ac509ee000ec.elb.us-east-1.amazonaws.com
      http:
        paths:
          - path: /ngos
            pathType: Prefix
            backend:
              service:
                name: ngo-service
                port:
                  number: 8081
          - path: /donations
            pathType: Prefix
            backend:
              service:
                name: donation-service
                port:
                  number: 8082
          - path: /volunteers
            pathType: Prefix
            backend:
              service:
                name: volunteer-service
                port:
                  number: 8083
