apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-deployment
  namespace: toggle-master
  labels:
    app: analytics
    tier: backend
    tags.datadoghq.com/env: "dev"
    tags.datadoghq.com/service: "analytics-service"
    tags.datadoghq.com/version: "1.0.0"
spec:
  selector:
    matchLabels:
      app: analytics
      tier: backend
  template:
    metadata:
      labels:
        app: analytics
        tier: backend
        tags.datadoghq.com/env: "dev"
        tags.datadoghq.com/service: "analytics-service"
        tags.datadoghq.com/version: "1.0.0"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8005"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: analytics-container
          image: 829281471119.dkr.ecr.us-east-1.amazonaws.com/toggle-master:analytics-service-5fa76155cf6bdaf0e46edc4bd174292d52d1d99a
          imagePullPolicy: Always
          ports:
            - containerPort: 8005
              name: http
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector.monitoring.svc.cluster.local:4317"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "grpc"
            - name: OTEL_EXPORTER_OTLP_INSECURE
              value: "true"
            
            - name: OTEL_TRACES_EXPORTER
              value: "otlp"
            - name: OTEL_LOGS_EXPORTER
              value: "otlp"
            - name: OTEL_METRICS_EXPORTER
              value: "none"
            
            - name: OTEL_SERVICE_NAME
              value: "analytics-service"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.name=analytics-service,deployment.environment=dev,k8s.cluster.name=toggle-master"
            
            - name: DD_ENV
              value: "dev"
            - name: DD_SERVICE
              value: "analytics-service"
            - name: DD_VERSION
              value: "1.0.0"
            - name: DD_LOGS_INJECTION
              value: "true"
            
          envFrom:
            - configMapRef:
                name: analytics-config
            - secretRef:
                name: analytics-secret
          
          resources:
            limits:
              memory: "512Mi"
              cpu: "1000m"
            requests:
              memory: "256Mi"
              cpu: "500m"
          
          startupProbe:
            httpGet:
              path: /health/startup
              port: 8005
            periodSeconds: 5
            failureThreshold: 30
          
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8005
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8005
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 3
