apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: toggle-master
  labels:
    app: auth
    tier: backend
    tags.datadoghq.com/env: "dev"
    tags.datadoghq.com/service: "auth-service"
    tags.datadoghq.com/version: "1.0.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
      tier: backend
  template:
    metadata:
      labels:
        app: auth
        tier: backend
        tags.datadoghq.com/env: "dev"
        tags.datadoghq.com/service: "auth-service"
        tags.datadoghq.com/version: "1.0.0"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8001"
        prometheus.io/path: "/metrics"
        admission.datadoghq.com/enabled: "true"
        ad.datadoghq.com/auth-container.checks: |
          {
            "openmetrics": {
              "instances": [
                {
                  "openmetrics_endpoint": "http://%%host%%:8001/metrics",
                  "namespace": "toggle_master",
                  "metrics": [
                    "http_requests_total",
                    "http_request_duration_seconds",
                    "process_cpu_seconds_total",
                    "process_resident_memory_bytes"
                  ]
                }
              ]
            }
          }
    spec:
      containers:
        - name: auth-container
          image: 951619424825.dkr.ecr.us-east-1.amazonaws.com/toggle-master:auth-service-4c423b0e0c3733b534c7e1ac69373625e4fac6ed
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
          env:
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_LOGS_INJECTION
              value: "true"
            - name: DD_ENV
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/env']
            - name: DD_SERVICE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/service']
            - name: DD_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/version']
          envFrom:
            - configMapRef:
                name: auth-config
            - secretRef:
                name: auth-secret
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"
