apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: toggle-master
  labels:
    app: auth
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
      tier: backend
  template:
    metadata:
      labels:
        app: auth
        tier: backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8001"
        prometheus.io/path: "/metrics"
        admission.datadoghq.com/enabled: "true"
    spec:
      containers:
        - name: auth-container
          image: 951619424825.dkr.ecr.us-east-1.amazonaws.com/toggle-master:auth-service-f30a10b3e2ed32799e24a11dca0e6ec80b7c2606
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
          envFrom:
            - configMapRef:
                name: auth-config
            - secretRef:
                name: auth-secret
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"
