apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: toggle-master
  labels:
    app: auth
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
      tier: backend
  template:
    metadata:
      labels:
        app: auth
        tier: backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8001"
        prometheus.io/path: "/metrics"
        admission.datadoghq.com/enabled: "true"
        ad.datadoghq.com/analytics-container.checks: |
          {
            "openmetrics": {
              "instances": [
                {
                  "openmetrics_endpoint": "http://%%host%%:8001/metrics",
                  "namespace": "toggle_master",
                  "metrics": [
                    "http_requests_total",
                    "http_request_duration_seconds",
                    "process_cpu_seconds_total",
                    "process_resident_memory_bytes"
                  ]
                }
              ]
            }
          }
    spec:
      containers:
        - name: auth-container
          image: 951619424825.dkr.ecr.us-east-1.amazonaws.com/toggle-master:auth-service-ead057b562b9f6d9f9769cf235a6ae48964a6818
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
          envFrom:
            - configMapRef:
                name: auth-config
            - secretRef:
                name: auth-secret
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"
