apiVersion: apps/v1
kind: Deployment
metadata:
  name: evaluation-deployment
  namespace: toggle-master
  labels:
    app: evaluation
    tier: backend
    tags.datadoghq.com/env: "dev"
    tags.datadoghq.com/service: "evaluation-service"
    tags.datadoghq.com/version: "1.0.0"
spec:
  selector:
    matchLabels:
      app: evaluation
      tier: backend
  template:
    metadata:
      labels:
        app: evaluation
        tier: backend
        tags.datadoghq.com/env: "dev"
        tags.datadoghq.com/service: "evaluation-service"
        tags.datadoghq.com/version: "1.0.0"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8004"
        prometheus.io/path: "/metrics"
        admission.datadoghq.com/enabled: "true"
        ad.datadoghq.com/evaluation-container.checks: |
          {
            "openmetrics": {
              "instances": [
                {
                  "openmetrics_endpoint": "http://%%host%%:8004/metrics",
                  "namespace": "toggle_master",
                  "metrics": [
                    "http_requests_total",
                    "http_request_duration_seconds",
                    "process_cpu_seconds_total",
                    "process_resident_memory_bytes"
                  ]
                }
              ]
            }
          }
    spec:
      containers:
        - name: evaluation-container
          image: 829281471119.dkr.ecr.us-east-1.amazonaws.com/toggle-master:evaluation-service-d142d4ef17f761ea9241aa741b2a95bf7cd32c2f
          imagePullPolicy: Always
          ports:
            - containerPort: 8004
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "otel-collector.monitoring.svc.cluster.local:4317"
            - name: OTEL_EXPORTER_OTLP_INSECURE
              value: "true"
            - name: OTEL_LOGS_EXPORTER
              value: "otlp"
            - name: OTEL_METRICS_EXPORTER
              value: "otlp"
            - name: OTEL_TRACES_EXPORTER
              value: "otlp"
            - name: OTEL_SERVICE_NAME
              value: "evaluation-service"
            - name: DD_LOGS_INJECTION
              value: "true"
            - name: DD_ENV
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/env']
            - name: DD_SERVICE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/service']
            - name: DD_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/version']
          envFrom:
            - configMapRef:
                name: evaluation-config
            - secretRef:
                name: evaluation-secret
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"
