apiVersion: apps/v1
kind: Deployment
metadata:
  name: evaluation-deployment
  namespace: toggle-master
  labels:
    app: evaluation
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evaluation
      tier: backend
  template:
    metadata:
      labels:
        app: evaluation
        tier: backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8004"
        prometheus.io/path: "/metrics"
        admission.datadoghq.com/enabled: "true"
    spec:
      containers:
        - name: evaluation-container
          image: 951619424825.dkr.ecr.us-east-1.amazonaws.com/toggle-master:evaluation-service-e3f76b7c943261a7edb33d5975ab63bb547b2bd2
          imagePullPolicy: Always
          ports:
            - containerPort: 8004
          envFrom:
            - configMapRef:
                name: evaluation-config
            - secretRef:
                name: evaluation-secret
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"
