apiVersion: apps/v1
kind: Deployment
metadata:
  name: flag-deployment
  namespace: toggle-master
  labels:
    app: flag
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flag
      tier: backend
  template:
    metadata:
      labels:
        app: flag
        tier: backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8002"
        prometheus.io/path: "/metrics"
        admission.datadoghq.com/enabled: "true"
    spec:
      containers:
        - name: flag-container
          image: 951619424825.dkr.ecr.us-east-1.amazonaws.com/toggle-master:flag-service-16b00e2be4a9927c7725df327214aeec67143024
          imagePullPolicy: Always
          ports:
            - containerPort: 8002
          envFrom:
            - configMapRef:
                name: flag-config
            - secretRef:
                name: flag-secret
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"
