apiVersion: apps/v1
kind: Deployment
metadata:
  name: flag-deployment
  namespace: toggle-master
  labels:
    app: flag
    tier: backend
    tags.datadoghq.com/env: "dev"
    tags.datadoghq.com/service: "flag-service"
    tags.datadoghq.com/version: "1.0.0"
spec:
  selector:
    matchLabels:
      app: flag
      tier: backend
  template:
    metadata:
      labels:
        app: flag
        tier: backend
        tags.datadoghq.com/env: "dev"
        tags.datadoghq.com/service: "flag-service"
        tags.datadoghq.com/version: "1.0.0"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8002"
        prometheus.io/path: "/metrics"
        admission.datadoghq.com/enabled: "true"
        ad.datadoghq.com/flag-container.checks: |
          {
            "openmetrics": {
              "instances": [
                {
                  "openmetrics_endpoint": "http://%%host%%:8002/metrics",
                  "namespace": "toggle_master",
                  "metrics": [
                    "http_requests_total",
                    "http_request_duration_seconds",
                    "process_cpu_seconds_total",
                    "process_resident_memory_bytes"
                  ]
                }
              ]
            }
          }
    spec:
      containers:
        - name: flag-container
          image: 829281471119.dkr.ecr.us-east-1.amazonaws.com/toggle-master:flag-service-061dde271f83367b73cc8c017d3edf8d54c20822
          imagePullPolicy: Always
          ports:
            - containerPort: 8002
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector.monitoring.svc.cluster.local:4318/v1/traces"
            - name: OTEL_EXPORTER_OTLP_INSECURE
              value: "true"
            - name: OTEL_LOGS_EXPORTER
              value: "otlp"
            - name: OTEL_METRICS_EXPORTER
              value: "otlp"
            - name: OTEL_TRACES_EXPORTER
              value: "otlp"
            - name: OTEL_SERVICE_NAME
              value: "flag-service"
            - name: DD_LOGS_INJECTION
              value: "true"
            - name: DD_ENV
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/env']
            - name: DD_SERVICE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/service']
            - name: DD_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/version']
          envFrom:
            - configMapRef:
                name: flag-config
            - secretRef:
                name: flag-secret
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"
