apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: toggle-master
  labels:
    app: auth
    monitored: "true"   # selecionado pelo ServiceMonitor
spec:
  type: ClusterIP
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 8001         
      targetPort: 8001
      name: http          # obrigatório para o ServiceMonitor referenciar por nome
