apiVersion: v1
kind: Service
metadata:
  name: targeting-service
  namespace: toggle-master
  labels:
    app: targeting
    monitored: "true"   # selecionado pelo ServiceMonitor
sspec:
  type: ClusterIP
  selector:
    app: targeting
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003
      name: http          # obrigatório para o ServiceMonitor referenciar por nome
