apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: toggle-master
spec:
  type: LoadBalancer
  selector:
    app: analytics
  loadBalancerIP: 172.21.0.100
  ports:
    - protocol: TCP
      port: 8005         
      targetPort: 8005
