apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-conf
  namespace: monitoring
data:
  otel-collector-config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      filelog:
        include: [ /var/log/pods/toggle-master*/*/**.log ]
        start_at: beginning
        include_file_path: true
        include_file_name: false

    processors:
      batch:
      k8sattributes:
        auth_type: "serviceAccount"
        passthrough: false
        extract:
          metadata: [k8s.pod.name, k8s.pod.uid, k8s.namespace.name, k8s.node.name, k8s.container.name]
      attributes:
        actions:
          - key: env
            from_attribute: deployment.environment
            action: insert
          - key: version
            from_attribute: service.version
            action: insert


    exporters:
      prometheusremotewrite:
        endpoint: "http://prometheus.monitoring.svc.cluster.local:9090/api/v1/write"
      loki:
        endpoint: "http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push"
      debug:
        verbosity: basic
      # doc - https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/datadogexporter/examples/collector.yaml
      datadog:
        host_metadata:
          enabled: true
          tags:
            - "env:dev"
        metrics:
          resource_attributes_as_tags: true 
        hostname: "otel-collector"
        api:
          key: "${DD_API_KEY}"
          site: "datadoghq.com"
        traces:
          compute_stats_by_span_kind: true
          span_name_as_resource_name: true
        retry_on_failure:
          enabled: true
          initial_interval: 5s
          max_interval: 30s

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch, k8sattributes, attributes]
          exporters: [datadog, debug] 
        metrics:
          receivers: [otlp]
          processors: [batch, k8sattributes]
          exporters: [prometheusremotewrite, datadog]
        logs:
          receivers: [filelog]
          processors: [batch, k8sattributes]
          exporters: [loki, datadog]
