name: Toggle-Master - Destroy

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Digite DESTROY para confirmar'
        required: true
  pull_request:
    branches: ["destroy"]

env:
  WORKING_DIR: fase_3/tech_challenge/toggle-master-microservices/terraform/

jobs:
  destroy:
    runs-on: ubuntu-latest
    if: github.event.inputs.confirm == 'DESTROY'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 🔑 Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Install Terragrunt
        uses: gruntwork-io/terragrunt-action@v3
        with:
          tg_version: '0.82.2'
          tofu_version: '1.10.1'

      - name: Terraform Init Backend
        run: |
          cd ${{ env.WORKING_DIR }}backend/
          terraform init

      - name: Terragrunt Destroy
        run: |
          cd ${{ env.WORKING_DIR }}
          terragrunt run --all --non-interactive destroy

      - name: Terraform Destroy Backend
        run: |
          cd ${{ env.WORKING_DIR }}backend/
          terraform destroy -auto-approve
