name: Terraform CI/CD - Develop

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 🔑 Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Lint Terraform
        uses: terraform-linters/setup-tflint@v1

      - name: Run TFLint
        working-directory: fase_3/tech_challenge/toggle-master-microservices/terraform/
        run: tflint

      - name: Terraform Init
        run: |
          cd fase_3/tech_challenge/toggle-master-microservices/terraform/backend/
          terraform init

      - name: Terraform Validate
        run: |
          cd fase_3/tech_challenge/toggle-master-microservices/terraform/backend/
          terraform validate

      - name: Terraform Plan Backend
        run: |
          cd fase_3/tech_challenge/toggle-master-microservices/terraform/backend/
          terraform plan

      - name: Terraform Apply Backend
        run: |
          cd fase_3/tech_challenge/toggle-master-microservices/terraform/backend/
          terraform apply -auto-approve

      - name: Install Terragrunt
        uses: gruntwork-io/terragrunt-action@v3
        with:
         tg_version: '0.82.2'
         tofu_version: '1.10.1'

      - name: Terragrunt plan
        run: |
          cd fase_3/tech_challenge/toggle-master-microservices/terraform/
          terragrunt plan --all

      - name: Terragrunt run
        run: |
          cd fase_3/tech_challenge/toggle-master-microservices/terraform/
          terragrunt run --all --non-interactive apply
